### ISSUE TITLE
why update graph.ndata['f'] and graph.edata['f']?

### ISSUE THREAD

**Issue by moonblue333** [amorehead/EGNN-DGL#1]
in my mind, we of use 'x' for node coords and 'f' for node and edge features.      if we want to update coords, we often define a new variable 'x_new' for coords;  and if we must compute 'hidden', use distance between nodes, use features in node or on edge.     that is, we DON'T directly update coords and features, especial features.     why do you update 'f'?  that is invariable from node and edge, you need to update 'h' and others intermediate variables.   thanks.

**Comment by amorehead** [comment]
@moonblue333,

Thank you for expressing interest in this repository. I believe your suggestions are valid. In short, my idea for this first implementation of the EGNN layer in DGL was to minimize the number of graph features (for nodes and edges), so I ended up directly replacing original node features with the learned node representations (what you refer to as node hidden features) to save memory (storing everything in graph.ndata['f']). In a future implementation of this layer, I am looking to implement a similar idea to what you have in mind, keeping copies of each version of node features (hidden or not) for users' convenience.

Of course, you are welcome to make such changes your self if you so desire, and I will gladly merge them into this project's main branch upon approval.

All the best!
